#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/dex-attribution-test.XXXXXX")"

cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

export HOME="$TMP_DIR/home"
export DEX_DIR="$ROOT"
export DX_STATE_DIR="$TMP_DIR/state"
export DX_LOOP_DIR="$TMP_DIR/loops"
export DX_ARTIFACT_DIR="$TMP_DIR/artifacts"
export DX_TOOL_DIR="$TMP_DIR/tools"
export DX_RUN_ROOT="$TMP_DIR/runs"

# shellcheck disable=SC1091
source "$ROOT/lib/common.sh"

assert_file() {
  [[ -f "$1" ]] || {
    printf 'missing file: %s\n' "$1" >&2
    exit 1
  }
}

assert_contains() {
  local needle="$1" file="$2"
  grep -qF "$needle" "$file" || {
    printf 'expected %s to contain %s\n' "$file" "$needle" >&2
    exit 1
  }
}

assert_not_contains() {
  local needle="$1" file="$2"
  if grep -qF "$needle" "$file"; then
    printf 'expected %s not to contain %s\n' "$file" "$needle" >&2
    exit 1
  fi
}

repo_dir="$TMP_DIR/repo"
mkdir -p "$repo_dir"
git -C "$repo_dir" init -q
git -C "$repo_dir" config user.email "dex@example.test"
git -C "$repo_dir" config user.name "Dex Test"

dx_install_repo_attribution "$repo_dir" > "$TMP_DIR/install.out"

[[ "$(git -C "$repo_dir" config core.hooksPath)" == ".dex/git-hooks" ]] || {
  printf 'core.hooksPath was not set to .dex/git-hooks\n' >&2
  exit 1
}
assert_file "$repo_dir/.dex/git-hooks/commit-msg"
assert_file "$repo_dir/.github/pull_request_template.md"
assert_contains "Generated by Dex" "$repo_dir/.github/pull_request_template.md"

printf 'first\n' > "$repo_dir/file.txt"
git -C "$repo_dir" add file.txt
git -C "$repo_dir" commit -q -m "feat: add file" -m "Generated with Claude Code" -m "Generated with [Claude Code](https://claude.ai/code)" -m "Co-Authored-By: Claude <noreply@anthropic.com>"

git -C "$repo_dir" log -1 --pretty=%B > "$TMP_DIR/commit-message.txt"
assert_contains "feat: add file" "$TMP_DIR/commit-message.txt"
assert_contains "Co-Authored-By: Dex <noreply@dexcode.ai>" "$TMP_DIR/commit-message.txt"
assert_not_contains "Generated with Claude Code" "$TMP_DIR/commit-message.txt"
assert_not_contains "Generated with [Claude Code]" "$TMP_DIR/commit-message.txt"
assert_not_contains "Co-Authored-By: Claude" "$TMP_DIR/commit-message.txt"

printf 'second\n' >> "$repo_dir/file.txt"
git -C "$repo_dir" add file.txt
git -C "$repo_dir" commit -q -m "fix: update file" -m "Co-Authored-By: Dex <noreply@dexcode.ai>"
git -C "$repo_dir" log -1 --pretty=%B > "$TMP_DIR/second-message.txt"
[[ "$(grep -cF "Co-Authored-By: Dex <noreply@dexcode.ai>" "$TMP_DIR/second-message.txt")" -eq 1 ]] || {
  printf 'Dex co-author trailer was duplicated\n' >&2
  exit 1
}

existing_repo="$TMP_DIR/existing-template"
mkdir -p "$existing_repo/.github"
git -C "$existing_repo" init -q
printf 'custom template\n' > "$existing_repo/.github/pull_request_template.md"
dx_install_repo_attribution "$existing_repo" > "$TMP_DIR/existing-install.out"
[[ "$(cat "$existing_repo/.github/pull_request_template.md")" == "custom template" ]] || {
  printf 'existing PR template was overwritten\n' >&2
  exit 1
}

printf 'attribution tests passed\n'
