#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/dex-attribution-test.XXXXXX")"

cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

export HOME="$TMP_DIR/home"
export DEX_DIR="$ROOT"
export DX_STATE_DIR="$TMP_DIR/state"
export DX_LOOP_DIR="$TMP_DIR/loops"
export DX_ARTIFACT_DIR="$TMP_DIR/artifacts"
export DX_TOOL_DIR="$TMP_DIR/tools"
export DX_RUN_ROOT="$TMP_DIR/runs"

# shellcheck disable=SC1091
source "$ROOT/lib/common.sh"

assert_file() {
  [[ -f "$1" ]] || {
    printf 'missing file: %s\n' "$1" >&2
    exit 1
  }
}

assert_contains() {
  local needle="$1" file="$2"
  grep -qF "$needle" "$file" || {
    printf 'expected %s to contain %s\n' "$file" "$needle" >&2
    exit 1
  }
}

assert_not_contains() {
  local needle="$1" file="$2"
  if grep -qF "$needle" "$file"; then
    printf 'expected %s not to contain %s\n' "$file" "$needle" >&2
    exit 1
  fi
}

run_command_bounded() {
  python3 - "$@" <<'PY'
import os
import signal
import subprocess
import sys

process = subprocess.Popen(
    sys.argv[1:],
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    start_new_session=True,
)
try:
    output, _ = process.communicate(timeout=5)
except subprocess.TimeoutExpired:
    os.killpg(process.pid, signal.SIGKILL)
    output, _ = process.communicate()
    sys.stdout.buffer.write(output)
    raise SystemExit(124)

sys.stdout.buffer.write(output)
raise SystemExit(process.returncode)
PY
}

repo_dir="$TMP_DIR/repo"
mkdir -p "$repo_dir"
git -C "$repo_dir" init -q
git -C "$repo_dir" config user.email "dex@example.test"
git -C "$repo_dir" config user.name "Dex Test"

dx_install_repo_attribution "$repo_dir" > "$TMP_DIR/install.out"

repo_hook_dir=$(dx_attribution_hook_dir "$repo_dir")
[[ "$(git -C "$repo_dir" config core.hooksPath)" == "$repo_hook_dir" ]] || {
  printf 'core.hooksPath was not set to the Dex hook proxy\n' >&2
  exit 1
}
assert_file "$repo_hook_dir/commit-msg"
assert_file "$repo_dir/.github/pull_request_template.md"
assert_contains "Generated by Dex" "$repo_dir/.github/pull_request_template.md"

printf 'first\n' > "$repo_dir/file.txt"
git -C "$repo_dir" add file.txt
git -C "$repo_dir" commit -q -m "feat: add file" -m "Generated with Claude Code" -m "Generated with [Claude Code](https://claude.ai/code)" -m "Co-Authored-By: Claude <noreply@anthropic.com>"

git -C "$repo_dir" log -1 --pretty=%B > "$TMP_DIR/commit-message.txt"
assert_contains "feat: add file" "$TMP_DIR/commit-message.txt"
assert_contains "Co-Authored-By: Dex <noreply@dexcode.ai>" "$TMP_DIR/commit-message.txt"
assert_not_contains "Generated with Claude Code" "$TMP_DIR/commit-message.txt"
assert_not_contains "Generated with [Claude Code]" "$TMP_DIR/commit-message.txt"
assert_not_contains "Co-Authored-By: Claude" "$TMP_DIR/commit-message.txt"

printf 'second\n' >> "$repo_dir/file.txt"
git -C "$repo_dir" add file.txt
git -C "$repo_dir" commit -q -m "fix: update file" -m "Co-Authored-By: Dex <noreply@dexcode.ai>"
git -C "$repo_dir" log -1 --pretty=%B > "$TMP_DIR/second-message.txt"
[[ "$(grep -cF "Co-Authored-By: Dex <noreply@dexcode.ai>" "$TMP_DIR/second-message.txt")" -eq 1 ]] || {
  printf 'Dex co-author trailer was duplicated\n' >&2
  exit 1
}

custom_message="$TMP_DIR/custom-message.txt"
printf 'feat: custom attribution\n' > "$custom_message"
DX_ATTRIBUTION_COAUTHOR_NAME="Dex Local" \
DX_ATTRIBUTION_COAUTHOR_EMAIL="dex-local@example.test" \
DEX_DIR="$ROOT" bash -c '
  set -euo pipefail
  source "$DEX_DIR/lib/common.sh"
  dx_commit_attribution_message "$1"
  dx_commit_attribution_message "$1"
' bash "$custom_message"
[[ "$(grep -cF "Co-Authored-By: Dex Local <dex-local@example.test>" "$custom_message")" -eq 1 ]] || {
  printf 'custom Dex co-author trailer was duplicated\n' >&2
  exit 1
}

existing_repo="$TMP_DIR/existing-template"
mkdir -p "$existing_repo/.github"
git -C "$existing_repo" init -q
printf 'custom template\n' > "$existing_repo/.github/pull_request_template.md"
dx_install_repo_attribution "$existing_repo" > "$TMP_DIR/existing-install.out"
[[ "$(cat "$existing_repo/.github/pull_request_template.md")" == "custom template" ]] || {
  printf 'existing PR template was overwritten\n' >&2
  exit 1
}

template_index=0
for template_name in pull_request_template.md PULL_REQUEST_TEMPLATE.md PULL_REQUEST_TEMPLATE; do
  template_index=$((template_index + 1))
  dangling_repo="$TMP_DIR/dangling-$template_index"
  dangling_target="$TMP_DIR/missing-$template_index"
  mkdir -p "$dangling_repo/.github"
  git -C "$dangling_repo" init -q
  ln -s "$dangling_target" "$dangling_repo/.github/$template_name"
  dx_install_repo_attribution "$dangling_repo" > "$TMP_DIR/dangling-install.out"
  [[ -L "$dangling_repo/.github/$template_name" ]] || {
    printf 'existing template symlink was overwritten: %s\n' "$template_name" >&2
    exit 1
  }
  [[ "$(readlink "$dangling_repo/.github/$template_name")" == "$dangling_target" ]]
  [[ ! -e "$dangling_target" ]] || {
    printf 'dangling template target was created: %s\n' "$template_name" >&2
    exit 1
  }
done

# The combined installer must stop after a hook failure even when its caller
# does not use errexit.
failure_repo="$TMP_DIR/failure-propagation"
mkdir -p "$failure_repo"
git -C "$failure_repo" init -q
failure_hook_dir=$(dx_attribution_hook_dir "$failure_repo")
mkdir -p "$failure_hook_dir"
printf '#!/usr/bin/env bash\nexit 0\n' > "$failure_hook_dir/commit-msg"
chmod +x "$failure_hook_dir/commit-msg"
set +e
dx_install_repo_attribution "$failure_repo" > "$TMP_DIR/failure-install.out" 2>&1
failure_status=$?
set -e
[[ "$failure_status" -ne 0 ]] || {
  printf 'combined attribution installer swallowed a hook failure\n' >&2
  exit 1
}
[[ ! -e "$failure_repo/.github/pull_request_template.md" ]] || {
  printf 'PR template was created after a hook installation failure\n' >&2
  exit 1
}

empty_config_repo="$TMP_DIR/empty-hook-config"
mkdir -p "$empty_config_repo"
git -C "$empty_config_repo" init -q
git -C "$empty_config_repo" config --local core.hooksPath ""
empty_config_state=$(dx_attribution_state_file "$empty_config_repo")
empty_config_hook_dir=$(dx_attribution_hook_dir "$empty_config_repo")
set +e
dx_install_attribution_hook "$empty_config_repo" > "$TMP_DIR/empty-config-install.out" 2>&1
empty_config_status=$?
set -e
[[ "$empty_config_status" -ne 0 ]]
[[ ! -e "$empty_config_state" ]]
[[ ! -e "$empty_config_hook_dir" ]]
[[ -z "$(git -C "$empty_config_repo" config --local --get core.hooksPath)" ]]
assert_contains "configured with an empty value" "$TMP_DIR/empty-config-install.out"

# Hook refreshes keep both the old and new receipts until every proxy has been
# replaced. A retry can therefore finish a refresh interrupted between files.
refresh_repo="$TMP_DIR/interrupted-hook-refresh"
mkdir -p "$refresh_repo"
git -C "$refresh_repo" init -q
dx_install_attribution_hook "$refresh_repo" > "$TMP_DIR/refresh-install.out"
refresh_state=$(dx_attribution_state_file "$refresh_repo")
refresh_proxy=$(dx_attribution_hook_dir "$refresh_repo")
refresh_original=$(__dx_attribution_state_get "$refresh_repo" original_hooks_path)
DEX_TEST_PROJECT_STATE_SCRIPT="$ROOT/scripts/project-state.py" \
DEX_TEST_REFRESH_STATE="$refresh_state" \
DEX_TEST_REFRESH_PROXY="$refresh_proxy" \
DEX_TEST_REFRESH_ORIGINAL="$refresh_original" python3 - <<'PY'
import importlib.util
import json
import os
from pathlib import Path

script = Path(os.environ["DEX_TEST_PROJECT_STATE_SCRIPT"])
spec = importlib.util.spec_from_file_location("dex_project_state", script)
module = importlib.util.module_from_spec(spec)
assert spec.loader is not None
spec.loader.exec_module(module)

state_path = Path(os.environ["DEX_TEST_REFRESH_STATE"])
hook_dir = Path(os.environ["DEX_TEST_REFRESH_PROXY"])
original_dir = Path(os.environ["DEX_TEST_REFRESH_ORIGINAL"])
new_dex_dir = "/opt/dex-after-upgrade"
real_replace = module.os.replace
writes = 0


def interrupt_second_proxy(source, destination):
    global writes
    destination = Path(destination)
    if destination.parent == hook_dir and destination.name in module.STANDARD_HOOKS:
        writes += 1
        if writes == 2:
            raise OSError("simulated interrupted hook refresh")
    return real_replace(source, destination)


module.os.replace = interrupt_second_proxy
try:
    module.attribution_generate(state_path, hook_dir, original_dir, new_dex_dir)
except OSError as exc:
    if "simulated interrupted" not in str(exc):
        raise
else:
    raise SystemExit("hook refresh did not reach the injected interruption")
finally:
    module.os.replace = real_replace

interrupted = json.loads(state_path.read_text(encoding="utf-8"))
if "pending_generated_hooks" not in interrupted:
    raise SystemExit("interrupted refresh lost its pending receipts")

module.attribution_generate(state_path, hook_dir, original_dir, new_dex_dir)
completed = module.read_attribution_state(state_path)
if "pending_generated_hooks" in completed:
    raise SystemExit("completed refresh retained its pending receipts")
for name, receipt in completed["generated_hooks"].items():
    if module.sha256_file(hook_dir / name) != receipt:
        raise SystemExit(f"proxy receipt mismatch after retry: {name}")
PY
dx_uninstall_repo_attribution "$refresh_repo" > "$TMP_DIR/refresh-uninstall.out"
[[ ! -e "$refresh_state" ]]
[[ ! -e "$refresh_proxy" ]]

template_failure_repo="$TMP_DIR/template-failure-propagation"
template_failure_target="$TMP_DIR/template-failure-target"
mkdir -p "$template_failure_repo" "$template_failure_target"
git -C "$template_failure_repo" init -q
ln -s "$template_failure_target" "$template_failure_repo/.github"
set +e
dx_install_repo_attribution "$template_failure_repo" > "$TMP_DIR/template-failure-install.out" 2>&1
template_failure_status=$?
set -e
[[ "$template_failure_status" -ne 0 ]] || {
  printf 'combined attribution installer swallowed a template failure\n' >&2
  exit 1
}
[[ ! -e "$template_failure_target/pull_request_template.md" ]] || {
  printf 'PR template was written through a symlinked directory\n' >&2
  exit 1
}

# A user hook that aliases the matching proxy is treated as the proxy itself,
# preventing symlink or hardlink recursion.
identity_repo="$TMP_DIR/hook-identity"
mkdir -p "$identity_repo/.githooks"
git -C "$identity_repo" init -q
git -C "$identity_repo" config user.email "dex@example.test"
git -C "$identity_repo" config user.name "Dex Test"
git -C "$identity_repo" config --local core.hooksPath .githooks
dx_install_attribution_hook "$identity_repo" > "$TMP_DIR/identity-install.out"
ln -s ../.git/dex-hooks/commit-msg "$identity_repo/.githooks/commit-msg"
printf 'identity\n' > "$identity_repo/value.txt"
git -C "$identity_repo" add value.txt
identity_status=0
run_command_bounded git -C "$identity_repo" commit -q -m "fix: avoid proxy recursion" \
  > "$TMP_DIR/identity-commit.out" 2>&1 || identity_status=$?
[[ "$identity_status" -eq 0 ]]
git -C "$identity_repo" log -1 --pretty=%B > "$TMP_DIR/identity-message.txt"
assert_contains "Co-Authored-By: Dex <noreply@dexcode.ai>" "$TMP_DIR/identity-message.txt"

# Installing the proxy must preserve Git's updateInstead behavior. A prior
# relative hook path can resolve back to the proxy for receive hooks, so this
# also exercises the runtime recursion guard.
push_target="$TMP_DIR/push-target"
push_source="$TMP_DIR/push-source"
mkdir -p "$push_target"
git -C "$push_target" init -q
git -C "$push_target" config user.email "dex@example.test"
git -C "$push_target" config user.name "Dex Test"
printf 'old\n' > "$push_target/value.txt"
git -C "$push_target" add value.txt
git -C "$push_target" commit -q -m "chore: initialize push target"
git -C "$push_target" config --local core.hooksPath dex-hooks
git -C "$push_target" config receive.denyCurrentBranch updateInstead
dx_install_attribution_hook "$push_target" > "$TMP_DIR/push-install.out"
push_proxy=$(dx_attribution_hook_dir "$push_target")
assert_file "$push_proxy/push-to-checkout"

git clone -q "$push_target" "$push_source"
git -C "$push_source" config user.email "dex@example.test"
git -C "$push_source" config user.name "Dex Test"
printf 'new\n' > "$push_source/value.txt"
git -C "$push_source" add value.txt
git -C "$push_source" commit -q -m "fix: update pushed value"
git -C "$push_source" push -q origin HEAD
[[ "$(cat "$push_target/value.txt")" == "new" ]]
[[ -z "$(git -C "$push_target" status --porcelain)" ]]
dx_uninstall_repo_attribution "$push_target" > "$TMP_DIR/push-uninstall.out"
[[ "$(git -C "$push_target" config --local --get core.hooksPath)" == "dex-hooks" ]]

# Absolute proxy paths are refreshed safely after a repository move. Default
# Git hooks are resolved from the current common Git directory at runtime.
relocate_init_old="$TMP_DIR/relocate-init-old"
relocate_init_new="$TMP_DIR/relocate-init-new"
mkdir -p "$relocate_init_old"
git -C "$relocate_init_old" init -q
git -C "$relocate_init_old" config user.email "dex@example.test"
git -C "$relocate_init_old" config user.name "Dex Test"
printf 'initial\n' > "$relocate_init_old/value.txt"
git -C "$relocate_init_old" add value.txt
git -C "$relocate_init_old" commit -q -m "chore: initialize relocation fixture"
dx_install_attribution_hook "$relocate_init_old" > "$TMP_DIR/relocate-initial-install.out"
relocate_old_proxy=$(dx_attribution_hook_dir "$relocate_init_old")
mv "$relocate_init_old" "$relocate_init_new"
relocate_new_proxy=$(dx_attribution_hook_dir "$relocate_init_new")
[[ "$relocate_old_proxy" != "$relocate_new_proxy" ]]
[[ "$(git -C "$relocate_init_new" config --local --get core.hooksPath)" == "$relocate_old_proxy" ]]

cat > "$relocate_init_new/.git/hooks/pre-commit" <<'HOOK'
#!/usr/bin/env bash
set -euo pipefail
printf 'default-hook\n' >> "$DEX_TEST_HOOK_LOG"
HOOK
chmod +x "$relocate_init_new/.git/hooks/pre-commit"
dx_install_attribution_hook "$relocate_init_new" > "$TMP_DIR/relocate-reinstall.out"
[[ "$(git -C "$relocate_init_new" config --local --get core.hooksPath)" == "$relocate_new_proxy" ]]
[[ "$(__dx_attribution_state_get "$relocate_init_new" installed_hooks_path)" == "$relocate_new_proxy" ]]
printf 'moved\n' >> "$relocate_init_new/value.txt"
git -C "$relocate_init_new" add value.txt
DEX_TEST_HOOK_LOG="$TMP_DIR/relocate-hook.log" \
  git -C "$relocate_init_new" commit -q -m "fix: verify relocated hook"
[[ "$(grep -c '^default-hook$' "$TMP_DIR/relocate-hook.log")" -eq 1 ]]
git -C "$relocate_init_new" log -1 --pretty=%B > "$TMP_DIR/relocate-message.txt"
assert_contains "Co-Authored-By: Dex <noreply@dexcode.ai>" "$TMP_DIR/relocate-message.txt"
dx_uninstall_repo_attribution "$relocate_init_new" > "$TMP_DIR/relocate-reinit-uninstall.out"
if git -C "$relocate_init_new" config --local --get core.hooksPath >/dev/null 2>&1; then
  printf 'relocated reinstall did not remove the Dex hook override\n' >&2
  exit 1
fi
[[ ! -e "$relocate_new_proxy" ]]

# Uninit also recognizes the recorded pre-move value without touching the old
# absolute path; cleanup is confined to the proxy that moved with the repo.
relocate_uninit_old="$TMP_DIR/relocate-uninit-old"
relocate_uninit_new="$TMP_DIR/relocate-uninit-new"
mkdir -p "$relocate_uninit_old/.githooks"
git -C "$relocate_uninit_old" init -q
git -C "$relocate_uninit_old" config --local core.hooksPath .githooks
dx_install_attribution_hook "$relocate_uninit_old" > "$TMP_DIR/relocate-uninit-install.out"
relocate_uninit_old_proxy=$(dx_attribution_hook_dir "$relocate_uninit_old")
mv "$relocate_uninit_old" "$relocate_uninit_new"
relocate_uninit_new_proxy=$(dx_attribution_hook_dir "$relocate_uninit_new")
relocate_uninit_state=$(dx_attribution_state_file "$relocate_uninit_new")
[[ "$(git -C "$relocate_uninit_new" config --local --get core.hooksPath)" == "$relocate_uninit_old_proxy" ]]
dx_uninstall_repo_attribution "$relocate_uninit_new" > "$TMP_DIR/relocate-direct-uninstall.out"
[[ "$(git -C "$relocate_uninit_new" config --local --get core.hooksPath)" == ".githooks" ]]
[[ ! -e "$relocate_uninit_new_proxy" ]]
[[ ! -e "$relocate_uninit_state" ]]

printf 'attribution tests passed\n'
