# shellcheck shell=bash
# Dex shared library — repo attribution bootstrap

DX_ATTRIBUTION_COAUTHOR_NAME="${DX_ATTRIBUTION_COAUTHOR_NAME:-Dex}"
DX_ATTRIBUTION_COAUTHOR_EMAIL="${DX_ATTRIBUTION_COAUTHOR_EMAIL:-noreply@dexcode.ai}"
DX_ATTRIBUTION_TRAILER="Co-Authored-By: ${DX_ATTRIBUTION_COAUTHOR_NAME} <${DX_ATTRIBUTION_COAUTHOR_EMAIL}>"

dx_attribution_hook_dir() {
  local repo_root="$1"
  printf '%s\n' "$repo_root/.dex/git-hooks"
}

dx_attribution_pr_template() {
  cat <<'EOF'
## Summary

## Testing

## Notes

Generated by Dex
EOF
}

dx_commit_attribution_message() {
  local message_file="$1"

  [[ -f "$message_file" ]] || return 0

  python3 - "$message_file" "$DX_ATTRIBUTION_TRAILER" <<'PY'
from pathlib import Path
import re
import sys

path = Path(sys.argv[1])
trailer = sys.argv[2]
text = path.read_text(encoding="utf-8", errors="surrogateescape")
has_final_newline = text.endswith("\n")
lines = text.splitlines()

claude_patterns = [
    re.compile(r"^\s*(?:Co-Authored-By|Co-authored-by):\s*Claude\b.*$", re.I),
    re.compile(r".*(?:Generated with .*Claude Code|Generated by Claude(?: Code)?|Created by Claude(?: Code)?|Authored(?: by| with) Claude(?: Code)?).*", re.I),
]

filtered = []
for line in lines:
    if any(pattern.match(line) for pattern in claude_patterns):
        continue
    filtered.append(line)

trailer_re = re.compile(r"^\s*Co-Authored-By:\s*Dex\s+<noreply@dexcode\.ai>\s*$", re.I)
if not any(trailer_re.match(line) for line in filtered):
    substantive = any(line.strip() and not line.lstrip().startswith("#") for line in filtered)
    if not substantive:
        new_text = "\n".join(filtered)
        if has_final_newline and new_text:
            new_text += "\n"
        path.write_text(new_text, encoding="utf-8", errors="surrogateescape")
        sys.exit(0)
    while filtered and filtered[-1] == "":
        filtered.pop()
    if filtered:
        filtered.extend(["", trailer])
    else:
        filtered.append(trailer)

new_text = "\n".join(filtered)
if has_final_newline or new_text:
    new_text += "\n"
path.write_text(new_text, encoding="utf-8", errors="surrogateescape")
PY
}

dx_install_attribution_hook() {
  local repo_root="$1"
  local hook_dir hook_file

  mkdir -p "$repo_root/.dex"
  hook_dir="$(dx_attribution_hook_dir "$repo_root")"
  mkdir -p "$hook_dir"
  hook_file="$hook_dir/commit-msg"

  cat > "${hook_file}.tmp" <<EOF
#!/usr/bin/env bash
# Dex-managed commit-msg hook. Re-run 'dx init' or 'dx sync' to refresh.
set -euo pipefail

DEX_DIR="\${DEX_DIR:-$DEX_DIR}"
# shellcheck disable=SC1091
source "\$DEX_DIR/lib/common.sh"
dx_commit_attribution_message "\$1"
EOF
  mv "${hook_file}.tmp" "$hook_file"
  chmod +x "$hook_file"

  if [[ -f "$hook_dir/prepare-commit-msg" ]] && grep -qF "Dex-managed prepare-commit-msg hook" "$hook_dir/prepare-commit-msg"; then
    rm -f "$hook_dir/prepare-commit-msg"
  fi

  git -C "$repo_root" config core.hooksPath ".dex/git-hooks"
  dx_done "Installed Dex commit attribution hook"
}

dx_install_pr_attribution_template() {
  local repo_root="$1"
  local template="$repo_root/.github/pull_request_template.md"
  local uppercase_template="$repo_root/.github/PULL_REQUEST_TEMPLATE.md"
  local template_dir="$repo_root/.github/PULL_REQUEST_TEMPLATE"

  if [[ -f "$template" || -f "$uppercase_template" || -d "$template_dir" ]]; then
    dx_ok "GitHub PR template already exists"
    return 0
  fi

  mkdir -p "$repo_root/.github"
  dx_attribution_pr_template > "${template}.tmp"
  mv "${template}.tmp" "$template"
  dx_done "Created GitHub PR template with Dex attribution"
}

dx_install_repo_attribution() {
  local repo_root="$1"

  dx_install_attribution_hook "$repo_root"
  dx_install_pr_attribution_template "$repo_root"
}
